## other configuration excluded from example...
exclude_patterns:
  - "tests/"
  - "public/css"
  - "public/js"
  - "src/DataFixtures"
  - "**/vendor/"
## je recopie les fichiers ignorés par default
  - "config/"
  - "db/"
  - "dist/"
  - "features/"
  - "**/node_modules/"
  - "script/"
  - "**/spec/"
  - "**/test/"
  - "**/tests/"
  - "Tests/"
  - "**/vendor/"
  - "**/*_test.go"
  - "**/*.d.ts"